### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by rikba** [swift-nav/libsettings#44]
Hi

we are currently implementing developing a [C++ ROS interface](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) to run our Piksi Multi rovers and base stations. libsettings seems to nicely wrap up the functionality to read and write settings to the device and would allow us to automatically configure the Piksi devices on startup. Do you have a link to a [C example](https://github.com/swift-nav/libsettings#example-usage) on how to use this library?

**Comment by silverjam** [comment]
Hi @rikba -- would you mind sending an email to support@swift-nav.com?  Then we can assign a support engineer to look at this!

**Comment by rikba** [comment]
Thank you, for now we implemented parameter settings using the libsbp c interface.
